### ISSUE TITLE
Fix executable builder

### ISSUE THREAD

**Issue by Rabios** [Rabios/raylib-v7#1]
# Brief

The executable builder provided inside raylib-v7 executable could build executables correctly...

However, There is problem which is that as raylib-v7 run with arguments, The JavaScript code inside built executable won't work!

### How to Help?

I need someone to edit `src/main.c` source code which contains executable builder, And provides someway to run JavaScript code from inside without needing to run with arguments...

### Alternative Solutions (If failed to solve)

We could split raylib-v7 into 2 executables, One to run JavaScript code and the other one to build executable that runs code...

**Comment by TSnake41** [comment]
I looked into the issue, them problem is that the raylib-wren builder (which is also used in raylib-v7) expects either a directory or a zip file when building.
If you give it a .js file, it will consider it as a zip file and not compress it.

You need to edit this part : `main.c:141`
```c
if (S_ISREG(st.st_mode)) {
    // Consider input as a bare bundle, just append file to get output.
    FILE* input = fopen(input_path, "rb");

    append_file(output, input);
    fclose(input);
}
```

to something like 
```c
if (S_ISREG(st.st_mode)) {
    mz_zip_archive zip;
    mz_zip_zero_struct(&zip);

    if (!mz_zip_writer_init_cfile(&zip, output, 0)) {
        puts("Can't initialize zip writter inside output.");
        return -1;
    }

    if (!mz_zip_writer_add_file(&zip, "main", input_path, NULL, 0,
        MZ_BEST_COMPRESSION)) {
        printf("miniz error: %x\n", mz_zip_get_last_error(&zip));
    }

    puts("Finalizing zip archive...");

    if (!mz_zip_writer_finalize_archive(&zip)) {
        puts("Can't finalize archive.");
        return -1;
    }
}
```

That will append a zip file with a main file (with the content of the input argument)

**Comment by Rabios** [comment]
@TSnake41 Thanks so much ❤️ !

Will keep this issue open, Once update raylib-v7 to use raylib 3.7, I'm gonna close it!
